name: password_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  get: 4.6.5
  pin_code_fields: 7.4.0
  
  get_storage: 2.0.3
  flutter: 
    sdk: flutter
  fluttertoast: ^8.1.2
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/MagadhLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

               
  
flutter: 
  uses-material-design: true

  assets:     
         - assets/images/

